### ISSUE TITLE
bracket error

### ISSUE THREAD

**Issue by mgpoole** [rin67630/Victron_VE_on_Steroids#2]
https://github.com/rin67630/Victron_VE_on_Steroids/blob/main/Software/b2_User_Functions.ino fails to compile with an error.

Line 139 should be
    if (String(keywords[i]) == "CS")    payload.ChSt = atoi(value[i]) * 10;

**Comment by rin67630** [comment]
Thank you for the correction ! 
You are right.
At my side it compiled without error, even after the misplaced bracket.
